CodingEventsRefresh/Models/ErrorViewModel.cs
namespace CodingEventsRefresh.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CodingEventsRefresh/Models/Event.cs
using System.Diagnostics;

namespace CodingEventsRefresh.Models
{
    public class Event
    {
        public string? Name { get; set; }
        public string? Description { get; set; }
        public string? ContactEmail { get; set; }
      
        public EventType Type { get; set; }
        public int Id { get; set; }

        public Event()
        {
        }

        public Event(string name, string description, string contactEmail)
        {
            Name = name;
            Description = description;
            ContactEmail = contactEmail;
        }

        public override string? ToString()
        {
            return Name;
        }

        public override bool Equals(object? obj)
        {
            return obj is Event @event &&
                   Id == @event.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }
}

CodingEventsRefresh/Models/EventCategory.cs
namespace CodingEventsRefresh.Models
{
    public class EventCategory
    {
        public int Id { get; set; }
        public string? Name { get; set; }

        public EventCategory() { }

        public EventCategory( string name)
        {
            Name = name;
        }


    }
}

CodingEventsRefresh/Models/EventType.cs
namespace CodingEventsRefresh.Models
{
    public enum EventType
    {
        Conference,
        Meetup,
        Workshop,
        Social
    }
}

CodingEventsRefresh/ViewModels/AddEventCategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CodingEventsRefresh.ViewModels
{
    public class AddEventCategoryViewModel
    {
        [Required(ErrorMessage = "Category name is required!")]
        [StringLength(20,MinimumLength = 3, ErrorMessage = "Name must be between 3 and 20 characters")]
        public string? CategoryName { get; set; }
    }
}

CodingEventsRefresh/ViewModels/AddEventViewModel.cs
using CodingEventsRefresh.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace CodingEventsRefresh.ViewModels
{
    public class AddEventViewModel
    {
        [Required(ErrorMessage = "Name is required.")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Name must be between 3 and 50 characters.")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Please enter a description for your event.")]
        [StringLength(500, ErrorMessage = "Description is too long!")]
        public string? Description { get; set; }

        [EmailAddress]
        public string? ContactEmail { get; set; }

        public EventType Type { get; set; }

        public List<SelectListItem> EventTypes { get; set; } = new List<SelectListItem>
        {
            new SelectListItem(EventType.Conference.ToString(), ((int)EventType.Conference).ToString()),
            new SelectListItem(EventType.Meetup.ToString(), ((int)EventType.Meetup).ToString()),
            new SelectListItem(EventType.Social.ToString(), ((int)EventType.Social).ToString()),
            new SelectListItem(EventType.Workshop.ToString(), ((int)EventType.Workshop).ToString())
        };
    }
}

CodingEventsRefresh/Controllers/EventCategoryController.cs
using CodingEventsRefresh.Data;
using CodingEventsRefresh.Models;
using CodingEventsRefresh.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CodingEventsRefresh.Controllers
{
    public class EventCategoryController : Controller
    {
        private EventDbContext context;
        public EventCategoryController(EventDbContext dbContext) 
        {
            context = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<EventCategory> categories = context.Categories.ToList();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            AddEventCategoryViewModel addEventCategoryViewModel = new AddEventCategoryViewModel();
            return View(addEventCategoryViewModel);
        }

        [HttpPost]
        public IActionResult ProcessCreateEventCategoryForm(AddEventCategoryViewModel addEventCategoryViewModel)
        {
            if (ModelState.IsValid)
            {
                EventCategory category = new EventCategory
                {
                    Name = addEventCategoryViewModel.CategoryName
                };
                context.Categories.Add(category);
                context.SaveChanges();

               return Redirect("/EventCategory");
            }

            return View(addEventCategoryViewModel);
        }
    }
}

CodingEventsRefresh/Controllers/EventsController.cs
using CodingEventsRefresh.Models;
using CodingEventsRefresh.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Diagnostics;
using System.Globalization;
using CodingEventsRefresh.ViewModels;

namespace CodingEventsRefresh.Controllers
{
    public class EventsController : Controller
    {

        private EventDbContext context;

        public EventsController(EventDbContext dbContext)
        {
            context = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Event> events = context.Events.ToList();
            
            return View(events);
        }

        [HttpGet]
        public IActionResult Add()
        {
            AddEventViewModel addEventViewModel = new AddEventViewModel();

            return View(addEventViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddEventViewModel addEventViewModel)
        {
            if (ModelState.IsValid)
            {
                Event newEvent = new Event
                {
                    Name = addEventViewModel.Name,
                    Description = addEventViewModel.Description,
                    ContactEmail = addEventViewModel.ContactEmail,
                    Type = addEventViewModel.Type
                };
                context.Events.Add(newEvent);
                context.SaveChanges();

                return Redirect("/Events");
            }
           return View(addEventViewModel); 
        }

        [HttpGet]
        [Route("/Events/Delete")]
        public IActionResult Delete()
        {
            ViewBag.events = context.Events.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Delete(int[] eventIds)
        {
            foreach(int eventId in eventIds)
            {
                Event? theEvent = context.Events.Find(eventId);
                context.Events.Remove(theEvent);
            }
            context.SaveChanges();

            return Redirect("/Events");
        }

    }
}

CodingEventsRefresh/Controllers/HomeController.cs
using CodingEventsRefresh.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CodingEventsRefresh.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CodingEventsRefresh/Views/EventCategory/Create.cshtml
@using CodingEventsRefresh.ViewModels
@model AddEventCategoryViewModel

<h1>Add Event Category</h1>

<form asp-controller="EventCategory" asp-action="ProcessCreateEventCategoryForm" method="post">
    <div class="form-group">
        <label asp-for="CategoryName">Category Name</label>
        <input asp-for="CategoryName" class="form-control" />
        <span asp-validation-for="CategoryName" class="text-danger"></span>
    </div>
    <input type="submit" value="Add Category" />
</form>

CodingEventsRefresh/Views/EventCategory/Index.cshtml
@model List<EventCategory>

<h1>Event Category</h1>

<table class="table">
    <tr>
        <th>Category Name</th>
    </tr>
    @foreach (EventCategory category in Model)
    {
        <tr>
            <td>@category.Name</td>
        </tr>
    }
</table>

CodingEventsRefresh/Views/Events/Add.cshtml
@using CodingEventsRefresh.ViewModels
@model AddEventViewModel

<h1>Add Event</h1>

<form asp-controller="Events" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ContactEmail">Contact Email</label>
        <input asp-for="ContactEmail" class="form-control" />
        <span asp-validation-for="ContactEmail" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type">Event Type</label>
        <select asp-for="Type" asp-items="Model.EventTypes"></select>
    </div>
    <input type="submit" value="Add Event" />
</form>

CodingEventsRefresh/Views/Events/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Delete Event</h1>

<form method="post">
    @foreach (var evt in ViewBag.events)
    {
        <div class="form-group">
            <label>
                <span>@evt.Name</span>
                <input type="checkbox" name="eventIds" value="@evt.Id" />
            </label>
        </div>
    }
        <input type="submit" value="Delete Selected Events" class="btn btn-danger" />
</form>

CodingEventsRefresh/Views/Events/Index.cshtml
@using CodingEventsRefresh.Models
@using CodingEventsRefresh.ViewModels
@model List<Event>

<h1>Coding Events</h1>

<p>
    <a asp-controller="Events" asp-action="Add">Add Event</a>
</p>

@if (Model.Count == 0)
{
    <p>No events yet!</p>
}
else
{
<table class="table">
        <tr>
            <th>
                ID
            </th>
            <th>
                Name
             </th>
            <th>
                Description
            </th>
            <th>
                Contact Email
            </th>
            <th>
                Event Type
            </th>
        </tr>
    @foreach (var evt in Model)
    {
        <tr>
            <td>@evt.Id</td>
            <td>@evt.Name</td>
            <td>@evt.Description</td>
            <td>@evt.ContactEmail</td>
            <td>@evt.Type</td>
        </tr>
    }
</table>
}

CodingEventsRefresh/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CodingEventsRefresh/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodingEventsRefresh</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CodingEventsRefresh.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodingEventsRefresh</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Add">Add event</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EventCategory" asp-action="Create">Create Event Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EventCategory" asp-action="Index">Event Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <main>
                @RenderBody()
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>
            </main>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CodingEventsRefresh - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>